name: "Test HWC"
description: "Test the HWC workflow for the application example"
  
runs:
  using: "composite"
  steps:
    - name: "Test hwc"
      shell: bash
      run: |
        rm -rf hwc/machine_x/hwc.gen
        apax hw_install_gsd
        apax hwc_setup_secure_communication
        apax hwc_import_certificate
        apax hwc_add_user
        apax hw_compile
    - name: "Test software"
      shell: bash
      run: |
        apax build
        apax test