name: "Test HWC"
description: "Test the HWC workflow for the application example"
  
runs:
  using: "composite"
  steps:
    - name: "Test hwc"
      shell: bash
      run: |
        # installl yq on image
        apt-get update
        apt-get install -y wget
        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        chmod +x /usr/bin/yq
        # delte exsting config for test
        rm -rf hwc/machine_x/hwc.gen
        # deactivate opc ua server in config > cause there is no lisenz on test agent
        yq eval '.Templates.Modules[0].Content.Services[] | select(.Type == "OpcUaServer").Enabled = false' --inplace hwc/hw_templates/cpu1516_v3_1.hwl.yaml
        apax hw_install_gsd
        apax hwc_setup_secure_communication
        apax hwc_import_certificate
        apax hwc_add_user
        apax hw_compile
    - name: "Test software"
      shell: bash
      run: |
        apax build
        apax test