name: "Test Application Example"
description: "Test the HWC workflow for the application example and do a software build"
  
runs:
  using: "composite"
  steps:
    - name: "test checked in secure settings"
        # when a customer  clone repository, the existing config needs to work after installation of gsds
      shell: bash
      run: | 
        apax hw_install_gsd
        apax hw_compile
    - name: "Setup test enviorment"
        # For test the scripts we need to delete the exsting secure config
      shell: bash
      run: | 
        # delte exsting config for test
        rm -rf hwc/machine_x/hwc.gen
    - name: "Test hwc scripts and workflow"
        # also the in the  piepline  create config will be  checked in, in package
      shell: bash
      run: |
        apax hwc_setup_secure_communication
        apax hwc_import_certificate
        apax hwc_add_user
        apax hw_compile
        # ------------------ Check if the secure config existing after compile to insert in package
        if [ -f 'hwc/machine_x/hwc.gen/cpu1516v31.HardwareIdentifiers.json' ]; 
        then
          echo 'cpu1516v31.HardwareIdentifiers.json exists.'
        else
          echo 'cpu1516v31.HardwareIdentifiers.json not exists.'
          exit 1
        fi
        if [ -f 'hwc/machine_x/hwc.gen/cpu1516v31.IoAddresses.json' ]; 
        then
          echo 'cpu1516v31.IoAddresses.json exists.'
        else
          echo 'cpu1516v31.IoAddresses.json not exists.'
          exit 1
        fi
        if [ -f 'hwc/machine_x/hwc.gen/cpu1516v31.SecurityConfiguration.json' ]; 
        then
          echo 'cpu1516v31.SecurityConfiguration.json exists.'
        else
          echo 'cpu1516v31.SecurityConfiguration.json not exists.'
          exit 1
        fi
    - name: "Build software"
      shell: bash
      run: |
        apax build