name: "Test HWC"
description: "Test the HWC workflow for the application example"
inputs:
  apax-token:
    description: "The token to authenticate with the SIMATIC AX registry"
    required: true
  
runs:
  using: "composite"
  steps:
    # This step is always required, since the SIMATIC AX tooling requires a login to the SIMATIC AX registry
    - name: Login to SIMATIC AX registry
      shell: bash
      env:
        APAX_TOKEN: ${{ inputs.apax-token }}
      run: |
        if [ -z "$APAX_TOKEN" ]; then
          echo "Error: APAX_TOKEN is empty"
          exit 1
        fi
        apax login --password "$APAX_TOKEN"

    - name: "Test hwc"
      shell: bash
      run: |
        apax hwc_setup_secure_communication
        apax hwc_import_certificate
        apax hwc_add_user
        apax hw_compile
        apax build
        apax test