# This workflow is going to be used during the development phase of the project
# The workflow builds and tests the the sources on the following triggers:
#   - once a change is pushed to the main branch or any of its sub-branches
name: Library development workflow

on:
  push:
    branches:
      - 'main'
      - 'main/**'
  pull_request:
    branches:
      - 'main'
      - 'main/**'
  workflow_call:
    secrets:
      APAX_TOKEN:
        required: true
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: read     # required for checkout
  packages: read     # required for pulling the container
  actions: write     # required for artifact uploading

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

      - name: Login to required registries
        uses: ./apax-login # change to simatic-ax/actions/apax-login@v3
        with:
          apax-token: ${{ secrets.APAX_TOKEN }}
          registries: |
            https://npm.pkg.github.com/,${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        uses: ./apax-install # change to simatic-ax/actions/apax-install@v3
        with:
          path: actions-test # only here for test purposes, remove later

      - name: Build source code
        uses: ./apax-build # change to simatic-ax/actions/apax-build@v3
        with:
          path: actions-test # only here for test purposes, remove later
          apax-build-targets: |
            llvm
            1500
          apax-build-args: |
            --debug
            --log Debug

      - name: Test source code
        uses: ./apax-test # change to simatic-ax/actions/apax-test@v3
        with:
          path: actions-test # only here for test purposes, remove later
          coverage: true
          loglevel: debug

      - name: Upload build artifacts
        if: ${{ github.event_name == 'workflow_call' || github.event_name == 'release'}}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |                 # only here for test purposes, alter later
            actions-test/bin/1500 
            actions-test/bin/llvm
          retention-days: 90
          if-no-files-found: error